apiVersion: v1
kind: Service
metadata:
  name: oom-demo
  namespace: oom-demo
spec:
  selector:
    app: oom-demo
  # NodePort: доступен извне через <node-ip>:<nodePort>
  # Для minikube: minikube service oom-demo -n oom-demo --url
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
